// <auto-generated />
using System;
using Hermes.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hermes.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Hermes.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("36fadeb8-2dcc-4b0a-8ea8-e7ec071c25f7"),
                            DeviceIdentifier = new Guid("49c2ea60-789c-457b-8e03-70c60097d9d5"),
                            IsActive = true,
                            IsDeleted = false,
                            RegisterDate = new DateTime(2022, 12, 25, 12, 23, 57, 420, DateTimeKind.Local).AddTicks(736),
                            UserName = "Mora"
                        },
                        new
                        {
                            Id = new Guid("38aa2230-9ffc-4375-8b07-c9e08bfaf829"),
                            DeviceIdentifier = new Guid("aa6588e0-818b-496c-b10f-2f6953bdd46c"),
                            IsActive = true,
                            IsDeleted = false,
                            RegisterDate = new DateTime(2022, 12, 25, 12, 23, 57, 420, DateTimeKind.Local).AddTicks(753),
                            UserName = "Ali"
                        },
                        new
                        {
                            Id = new Guid("92b49dc0-ecb6-4888-b996-baaded0c9627"),
                            DeviceIdentifier = new Guid("4610790d-c36b-468f-9894-e80d27d611e8"),
                            IsActive = true,
                            IsDeleted = false,
                            RegisterDate = new DateTime(2022, 12, 25, 12, 23, 57, 420, DateTimeKind.Local).AddTicks(756),
                            UserName = "Mehran"
                        },
                        new
                        {
                            Id = new Guid("64bfc194-9ad2-45d6-b3b8-8aedad21d52e"),
                            DeviceIdentifier = new Guid("a946daaf-e128-4e19-8690-dbccb568986e"),
                            IsActive = true,
                            IsDeleted = false,
                            RegisterDate = new DateTime(2022, 12, 25, 12, 23, 57, 420, DateTimeKind.Local).AddTicks(758),
                            UserName = "Babak"
                        },
                        new
                        {
                            Id = new Guid("bad1e3e6-60d5-4610-b017-2b63ab6341e6"),
                            DeviceIdentifier = new Guid("e413ab3e-c937-40cb-98d2-f70e0bc5b947"),
                            IsActive = true,
                            IsDeleted = false,
                            RegisterDate = new DateTime(2022, 12, 25, 12, 23, 57, 420, DateTimeKind.Local).AddTicks(765),
                            UserName = "Sara"
                        },
                        new
                        {
                            Id = new Guid("ec88ef4e-77ea-44da-947f-1dc76f9fd4bd"),
                            DeviceIdentifier = new Guid("b93a51d7-a661-4898-ac70-76c0f2aa1275"),
                            IsActive = true,
                            IsDeleted = false,
                            RegisterDate = new DateTime(2022, 12, 25, 12, 23, 57, 420, DateTimeKind.Local).AddTicks(768),
                            UserName = "Ahad"
                        },
                        new
                        {
                            Id = new Guid("6fb6da98-62c5-421f-9a21-e71c0c7dc821"),
                            DeviceIdentifier = new Guid("5306cb47-6c5c-46e5-96ef-704bba535e11"),
                            IsActive = true,
                            IsDeleted = false,
                            RegisterDate = new DateTime(2022, 12, 25, 12, 23, 57, 420, DateTimeKind.Local).AddTicks(770),
                            UserName = "Reza"
                        },
                        new
                        {
                            Id = new Guid("7c4b3b2e-90db-41d9-a08b-046632463035"),
                            DeviceIdentifier = new Guid("86fe9d3b-7d95-402b-8dd4-b87d101bf408"),
                            IsActive = true,
                            IsDeleted = false,
                            RegisterDate = new DateTime(2022, 12, 25, 12, 23, 57, 420, DateTimeKind.Local).AddTicks(772),
                            UserName = "Maryam"
                        },
                        new
                        {
                            Id = new Guid("83a7b79f-3250-4b55-8fa2-267f13e7bfaa"),
                            DeviceIdentifier = new Guid("fab59f16-5d35-4bd3-b294-2996de7e291d"),
                            IsActive = true,
                            IsDeleted = false,
                            RegisterDate = new DateTime(2022, 12, 25, 12, 23, 57, 420, DateTimeKind.Local).AddTicks(774),
                            UserName = "Saeid"
                        },
                        new
                        {
                            Id = new Guid("de2b83db-0d80-4c7d-b360-a171c4c6bcac"),
                            DeviceIdentifier = new Guid("ab2f4cae-bf89-45a2-a38e-63e06bd5c0af"),
                            IsActive = true,
                            IsDeleted = false,
                            RegisterDate = new DateTime(2022, 12, 25, 12, 23, 57, 420, DateTimeKind.Local).AddTicks(777),
                            UserName = "Saman"
                        },
                        new
                        {
                            Id = new Guid("18bf0830-2bf9-4f2a-a308-264c79226f56"),
                            DeviceIdentifier = new Guid("023688aa-cd06-4735-9b07-65a6bc73b931"),
                            IsActive = true,
                            IsDeleted = false,
                            RegisterDate = new DateTime(2022, 12, 25, 12, 23, 57, 420, DateTimeKind.Local).AddTicks(779),
                            UserName = "Aidin"
                        });
                });

            modelBuilder.Entity("Hermes.Domain.Entities.UserMessage", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("DeviceId");

                    b.ToTable("UserMessages");

                    b.HasData(
                        new
                        {
                            DeviceId = new Guid("49c2ea60-789c-457b-8e03-70c60097d9d5"),
                            Content = "TestMessage",
                            Status = false
                        },
                        new
                        {
                            DeviceId = new Guid("aa6588e0-818b-496c-b10f-2f6953bdd46c"),
                            Content = "TestMessage",
                            Status = false
                        },
                        new
                        {
                            DeviceId = new Guid("4610790d-c36b-468f-9894-e80d27d611e8"),
                            Content = "TestMessage",
                            Status = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
